apiVersion: v1
kind: Service
metadata:
  name: devops-project-app-service
  labels:
    app: devops-project-app 
spec:
  selector:
    app: devops-project-app
  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
