apiVersion: v1
kind: Service
metadata:
  name: devops-project-7-app-service
  labels:
    app: devops-project-7-app 
spec:
  selector:
    app: devops-project-7-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
